-- XX wants to contact the host of the listing number 22 to request an extra mattress for her friend. Her booking id is 34.


-- INSERT INTO message (sourceId, targetId,message)  
-- VALUES ((SELECT user_id FROM booking WHERE id = 22), 
-- (SELECT hostId FROM listing WHERE id = (SELECT listing_id FROM booking WHERE id = 22))
-- ,"MSEEAGEHERE");

-- SELECT * FROM message;

-- SELECT hostId FROM listing WHERE id = (SELECT listing_id FROM booking WHERE id = 22);

-- Admin wants to know the total revenue generated by the system between 1st July and 30th of Aug
-- SELECT SUM(company_charge) FROM transaction ts INNER JOIN booking b ON ts.booking_id = b.id 
-- WHERE b.start_date > '2022-07-01' AND b.start_date < '2022-08-01' AND ts.billing_status = 'paid';

SELECT SUM(company_charge) FROM transaction ts INNER JOIN booking b ON ts.booking_id = b.id 
;

