USE residex;
insert into message (id, sourceId, targetId, message, updatedAt, status) values (1, 234, 235, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', '2023-01-01 03:42:20', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (2, 99, 210, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (3, 180, 229, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2023-01-06 17:15:35', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (4, 192, 100, 'Phasellus id sapien in sapien iaculis congue.', '2024-04-09 17:10:22', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (5, 81, 251, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (6, 201, 281, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (7, 173, 174, 'Vivamus in felis eu sapien cursus vestibulum.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (8, 94, 250, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (9, 110, 228, 'In congue. Etiam justo.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (10, 236, 173, 'Proin at turpis a pede posuere nonummy. Integer non velit.', '2024-06-19 11:29:32', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (11, 146, 159, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (12, 108, 9, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (13, 133, 175, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2024-06-07 23:53:43', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (14, 229, 233, 'Curabitur convallis.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (15, 190, 200, 'Phasellus in felis. Donec semper sapien a libero.', '2023-11-26 08:25:22', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (16, 89, 291, 'Duis at velit eu est congue elementum.', '2023-12-04 02:21:58', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (17, 43, 141, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', '2023-08-23 08:41:51', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (18, 6, 176, 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', '2023-05-05 07:55:18', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (19, 30, 190, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', '2023-01-17 17:46:40', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (20, 228, 201, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2022-12-01 07:46:31', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (21, 189, 157, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', '2023-04-19 23:48:21', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (22, 98, 131, 'Integer a nibh. In quis justo.', '2023-12-16 21:39:36', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (23, 268, 107, 'Suspendisse potenti. In eleifend quam a odio.', '2023-10-27 20:38:36', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (24, 151, 74, 'Nunc purus.', '2023-04-05 16:11:21', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (25, 119, 30, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', '2023-07-24 03:28:07', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (26, 259, 261, 'Quisque ut erat.', '2024-04-08 03:15:34', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (27, 283, 175, 'Proin interdum mauris non ligula pellentesque ultrices.', '2024-02-16 03:19:48', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (28, 230, 147, 'Integer tincidunt ante vel ipsum.', '2023-07-31 15:54:42', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (29, 76, 46, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', '2024-05-02 01:10:36', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (30, 244, 6, 'Suspendisse potenti.', '2024-02-12 09:19:57', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (31, 229, 236, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', '2023-10-01 18:27:10', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (32, 250, 156, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', '2024-03-08 08:02:03', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (33, 122, 147, 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2023-05-28 01:31:57', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (34, 209, 94, 'Cras in purus eu magna vulputate luctus.', '2024-06-23 20:20:36', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (35, 66, 44, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (36, 3, 39, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', '2023-11-10 18:25:42', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (37, 240, 1, 'Nulla ac enim.', '2024-01-03 01:34:05', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (38, 259, 187, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', '2023-09-04 10:24:21', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (39, 70, 119, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2024-04-27 14:15:03', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (40, 261, 127, 'Sed vel enim sit amet nunc viverra dapibus.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (41, 142, 71, 'Proin risus. Praesent lectus.', '2023-02-14 05:52:39', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (42, 156, 63, 'Donec ut dolor.', '2023-02-06 06:10:42', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (43, 2, 266, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', '2023-04-06 20:50:09', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (44, 170, 209, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (45, 176, 47, 'Etiam vel augue.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (46, 141, 25, 'Quisque id justo sit amet sapien dignissim vestibulum.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (47, 243, 31, 'Integer a nibh.', '2024-03-31 13:36:56', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (48, 63, 4, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2024-03-28 14:21:10', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (49, 214, 198, 'Duis consequat dui nec nisi volutpat eleifend.', '2023-06-21 08:42:47', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (50, 146, 190, 'Duis at velit eu est congue elementum.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (51, 202, 170, 'Nam dui.', '2024-07-20 08:03:19', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (52, 40, 260, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', '2023-10-22 14:15:04', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (53, 80, 295, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (54, 114, 249, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (55, 188, 154, 'Pellentesque at nulla. Suspendisse potenti.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (56, 48, 63, 'Phasellus sit amet erat.', '2023-02-16 21:10:56', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (57, 286, 171, 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', '2023-05-06 13:05:37', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (58, 231, 90, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', '2022-12-20 00:58:55', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (59, 271, 181, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '2023-08-12 07:19:08', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (60, 47, 7, 'Duis consequat dui nec nisi volutpat eleifend.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (61, 137, 169, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (62, 256, 123, 'Aenean sit amet justo.', '2023-10-25 12:32:17', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (63, 298, 178, 'Aliquam erat volutpat. In congue.', '2023-07-22 09:27:46', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (64, 94, 299, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', '2024-07-21 13:14:34', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (65, 229, 85, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (66, 89, 112, 'Etiam vel augue. Vestibulum rutrum rutrum neque.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (67, 68, 274, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2024-05-20 23:49:06', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (68, 275, 204, 'Pellentesque at nulla.', '2024-03-07 20:30:27', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (69, 235, 132, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (70, 44, 126, 'Nulla facilisi.', '2023-11-06 14:26:49', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (71, 271, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (72, 263, 50, 'Morbi ut odio.', '2024-01-08 21:59:30', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (73, 42, 44, 'Phasellus sit amet erat.', '2024-05-26 04:43:41', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (74, 212, 194, 'Duis mattis egestas metus. Aenean fermentum.', '2023-04-07 00:41:18', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (75, 297, 92, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2024-02-21 02:47:39', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (76, 213, 227, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2023-06-15 15:06:35', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (77, 231, 5, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', null, 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (78, 276, 11, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', '2024-05-08 01:19:44', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (79, 234, 297, 'Etiam vel augue.', '2024-04-12 09:45:30', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (80, 28, 296, 'In eleifend quam a odio.', '2023-01-20 00:10:17', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (81, 93, 206, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', '2024-02-11 16:38:53', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (82, 187, 218, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '2024-03-11 21:03:45', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (83, 163, 135, 'Donec semper sapien a libero. Nam dui.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (84, 82, 73, 'Nunc purus.', '2023-12-02 22:12:07', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (85, 25, 244, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2024-05-16 00:44:44', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (86, 241, 108, 'Quisque id justo sit amet sapien dignissim vestibulum.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (87, 233, 290, 'Integer a nibh. In quis justo.', '2023-01-04 13:41:40', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (88, 137, 198, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '2024-04-06 04:12:12', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (89, 141, 150, 'Praesent blandit lacinia erat.', '2024-05-02 22:14:42', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (90, 88, 51, 'Mauris lacinia sapien quis libero.', '2023-03-21 00:52:17', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (91, 6, 170, 'Phasellus sit amet erat.', '2024-05-26 03:44:48', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (92, 137, 109, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', '2022-12-23 02:05:16', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (93, 57, 202, 'Integer ac neque.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (94, 224, 201, 'Proin eu mi.', '2023-01-03 22:49:00', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (95, 88, 28, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', '2023-08-09 13:17:41', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (96, 66, 151, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', '2023-06-03 04:21:26', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (97, 57, 171, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2024-06-09 19:15:23', 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (98, 102, 239, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', null, 'received');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (99, 12, 136, 'Suspendisse potenti. Nullam porttitor lacus at turpis.', '2023-07-03 19:40:12', 'read');
insert into message (id, sourceId, targetId, message, updatedAt, status) values (100, 267, 237, 'Sed ante.', '2023-11-16 22:24:56', 'received');
