

insert into review (id, bookingId, Rating, comment) values (1, 72, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into review (id, bookingId, Rating, comment) values (2, 127, 2, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (3, 169, 5, 'Morbi non quam nec dui luctus rutrum.');
insert into review (id, bookingId, Rating, comment) values (4, 603, 2, 'Sed sagittis.');
insert into review (id, bookingId, Rating, comment) values (5, 645, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into review (id, bookingId, Rating, comment) values (6, 606, 3, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into review (id, bookingId, Rating, comment) values (7, 637, 3, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into review (id, bookingId, Rating, comment) values (8, 590, 1, 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into review (id, bookingId, Rating, comment) values (9, 480, 3, 'Cras in purus eu magna vulputate luctus.');
insert into review (id, bookingId, Rating, comment) values (10, 372, 3, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into review (id, bookingId, Rating, comment) values (11, 568, 3, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into review (id, bookingId, Rating, comment) values (12, 249, 3, 'Nunc purus.');
insert into review (id, bookingId, Rating, comment) values (13, 121, 4, 'Mauris lacinia sapien quis libero.');
insert into review (id, bookingId, Rating, comment) values (14, 536, 2, 'Curabitur at ipsum ac tellus semper interdum.');
insert into review (id, bookingId, Rating, comment) values (15, 389, 1, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into review (id, bookingId, Rating, comment) values (16, 339, 2, 'Nulla facilisi.');
insert into review (id, bookingId, Rating, comment) values (17, 493, 2, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (18, 314, 2, 'Nam nulla.');
insert into review (id, bookingId, Rating, comment) values (19, 122, 1, 'Mauris ullamcorper purus sit amet nulla.');
insert into review (id, bookingId, Rating, comment) values (20, 651, 5, 'Sed accumsan felis.');
insert into review (id, bookingId, Rating, comment) values (21, 430, 3, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into review (id, bookingId, Rating, comment) values (22, 98, 3, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into review (id, bookingId, Rating, comment) values (23, 519, 3, 'Vivamus tortor.');
insert into review (id, bookingId, Rating, comment) values (24, 202, 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into review (id, bookingId, Rating, comment) values (25, 606, 5, 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into review (id, bookingId, Rating, comment) values (26, 493, 1, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into review (id, bookingId, Rating, comment) values (27, 484, 1, 'Proin risus.');
insert into review (id, bookingId, Rating, comment) values (28, 557, 5, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (29, 629, 2, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into review (id, bookingId, Rating, comment) values (30, 52, 5, 'Fusce consequat.');
insert into review (id, bookingId, Rating, comment) values (31, 529, 4, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into review (id, bookingId, Rating, comment) values (32, 329, 2, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into review (id, bookingId, Rating, comment) values (33, 279, 3, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (34, 252, 5, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into review (id, bookingId, Rating, comment) values (35, 277, 2, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into review (id, bookingId, Rating, comment) values (36, 658, 3, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into review (id, bookingId, Rating, comment) values (37, 332, 3, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into review (id, bookingId, Rating, comment) values (38, 325, 1, 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into review (id, bookingId, Rating, comment) values (39, 241, 5, 'Pellentesque eget nunc.');
insert into review (id, bookingId, Rating, comment) values (40, 691, 5, 'Duis consequat dui nec nisi volutpat eleifend.');
insert into review (id, bookingId, Rating, comment) values (41, 457, 4, 'Nullam molestie nibh in lectus.');
insert into review (id, bookingId, Rating, comment) values (42, 125, 3, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (43, 165, 3, 'Phasellus sit amet erat. Nulla tempus.');
insert into review (id, bookingId, Rating, comment) values (44, 28, 5, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into review (id, bookingId, Rating, comment) values (45, 551, 3, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into review (id, bookingId, Rating, comment) values (46, 433, 4, 'Nulla justo.');
insert into review (id, bookingId, Rating, comment) values (47, 283, 5, 'Integer ac neque. Duis bibendum.');
insert into review (id, bookingId, Rating, comment) values (48, 608, 4, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (49, 212, 2, 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into review (id, bookingId, Rating, comment) values (50, 275, 1, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into review (id, bookingId, Rating, comment) values (51, 138, 4, 'Nunc rhoncus dui vel sem.');
insert into review (id, bookingId, Rating, comment) values (52, 236, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into review (id, bookingId, Rating, comment) values (53, 550, 3, 'Mauris lacinia sapien quis libero.');
insert into review (id, bookingId, Rating, comment) values (54, 243, 5, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (55, 246, 1, 'Donec ut dolor.');
insert into review (id, bookingId, Rating, comment) values (56, 81, 1, 'Etiam vel augue.');
insert into review (id, bookingId, Rating, comment) values (57, 607, 3, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into review (id, bookingId, Rating, comment) values (58, 161, 3, 'Etiam vel augue.');
insert into review (id, bookingId, Rating, comment) values (59, 386, 1, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into review (id, bookingId, Rating, comment) values (60, 31, 3, 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into review (id, bookingId, Rating, comment) values (61, 400, 4, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into review (id, bookingId, Rating, comment) values (62, 385, 2, 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into review (id, bookingId, Rating, comment) values (63, 603, 5, 'Proin at turpis a pede posuere nonummy.');
insert into review (id, bookingId, Rating, comment) values (64, 360, 1, 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into review (id, bookingId, Rating, comment) values (65, 401, 4, 'Integer ac neque.');
insert into review (id, bookingId, Rating, comment) values (66, 592, 4, 'Nulla ut erat id mauris vulputate elementum.');
insert into review (id, bookingId, Rating, comment) values (67, 107, 4, 'Donec vitae nisi.');
insert into review (id, bookingId, Rating, comment) values (68, 384, 5, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into review (id, bookingId, Rating, comment) values (69, 430, 5, 'Aenean fermentum.');
insert into review (id, bookingId, Rating, comment) values (70, 281, 1, 'Donec semper sapien a libero.');
insert into review (id, bookingId, Rating, comment) values (71, 388, 2, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into review (id, bookingId, Rating, comment) values (72, 669, 5, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into review (id, bookingId, Rating, comment) values (73, 617, 4, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into review (id, bookingId, Rating, comment) values (74, 337, 5, 'Maecenas tincidunt lacus at velit.');
insert into review (id, bookingId, Rating, comment) values (75, 388, 1, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into review (id, bookingId, Rating, comment) values (76, 259, 2, 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into review (id, bookingId, Rating, comment) values (77, 582, 3, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into review (id, bookingId, Rating, comment) values (78, 92, 2, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into review (id, bookingId, Rating, comment) values (79, 152, 5, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into review (id, bookingId, Rating, comment) values (80, 29, 3, 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into review (id, bookingId, Rating, comment) values (81, 516, 3, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (82, 290, 4, 'Nunc rhoncus dui vel sem.');
insert into review (id, bookingId, Rating, comment) values (83, 220, 5, 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into review (id, bookingId, Rating, comment) values (84, 420, 1, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into review (id, bookingId, Rating, comment) values (85, 19, 2, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into review (id, bookingId, Rating, comment) values (86, 513, 1, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into review (id, bookingId, Rating, comment) values (87, 601, 4, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into review (id, bookingId, Rating, comment) values (88, 210, 5, 'Aenean lectus. Pellentesque eget nunc.');
insert into review (id, bookingId, Rating, comment) values (89, 234, 4, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into review (id, bookingId, Rating, comment) values (90, 585, 1, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into review (id, bookingId, Rating, comment) values (91, 258, 1, 'Vivamus tortor.');
insert into review (id, bookingId, Rating, comment) values (92, 423, 5, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into review (id, bookingId, Rating, comment) values (93, 529, 3, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into review (id, bookingId, Rating, comment) values (94, 196, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into review (id, bookingId, Rating, comment) values (95, 330, 3, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into review (id, bookingId, Rating, comment) values (96, 690, 2, 'Aliquam non mauris.');
insert into review (id, bookingId, Rating, comment) values (97, 6, 5, 'Duis bibendum.');
insert into review (id, bookingId, Rating, comment) values (98, 610, 5, 'Phasellus in felis.');
insert into review (id, bookingId, Rating, comment) values (99, 354, 5, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into review (id, bookingId, Rating, comment) values (100, 427, 1, 'In blandit ultrices enim.');
insert into review (id, bookingId, Rating, comment) values (101, 40, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into review (id, bookingId, Rating, comment) values (102, 100, 5, 'In congue.');
insert into review (id, bookingId, Rating, comment) values (103, 1, 3, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into review (id, bookingId, Rating, comment) values (104, 478, 5, 'Donec ut dolor.');
insert into review (id, bookingId, Rating, comment) values (105, 249, 1, 'Nunc purus. Phasellus in felis.');
insert into review (id, bookingId, Rating, comment) values (106, 679, 3, 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into review (id, bookingId, Rating, comment) values (107, 95, 4, 'Nullam varius. Nulla facilisi.');
insert into review (id, bookingId, Rating, comment) values (108, 652, 4, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into review (id, bookingId, Rating, comment) values (109, 367, 2, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into review (id, bookingId, Rating, comment) values (110, 626, 4, 'Mauris ullamcorper purus sit amet nulla.');
insert into review (id, bookingId, Rating, comment) values (111, 14, 3, 'Sed sagittis.');
insert into review (id, bookingId, Rating, comment) values (112, 141, 2, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into review (id, bookingId, Rating, comment) values (113, 324, 2, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into review (id, bookingId, Rating, comment) values (114, 272, 1, 'Praesent blandit lacinia erat.');
insert into review (id, bookingId, Rating, comment) values (115, 19, 4, 'Nam dui.');
insert into review (id, bookingId, Rating, comment) values (116, 489, 4, 'Nulla tellus.');
insert into review (id, bookingId, Rating, comment) values (117, 388, 2, 'Integer non velit.');
insert into review (id, bookingId, Rating, comment) values (118, 310, 3, 'Vestibulum rutrum rutrum neque.');
insert into review (id, bookingId, Rating, comment) values (119, 149, 5, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into review (id, bookingId, Rating, comment) values (120, 88, 2, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into review (id, bookingId, Rating, comment) values (121, 68, 5, 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into review (id, bookingId, Rating, comment) values (122, 322, 5, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into review (id, bookingId, Rating, comment) values (123, 540, 5, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into review (id, bookingId, Rating, comment) values (124, 597, 3, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into review (id, bookingId, Rating, comment) values (125, 462, 3, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into review (id, bookingId, Rating, comment) values (126, 72, 1, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into review (id, bookingId, Rating, comment) values (127, 478, 4, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into review (id, bookingId, Rating, comment) values (128, 95, 1, 'Praesent blandit.');
insert into review (id, bookingId, Rating, comment) values (129, 576, 2, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into review (id, bookingId, Rating, comment) values (130, 9, 1, 'Donec dapibus.');
insert into review (id, bookingId, Rating, comment) values (131, 166, 5, 'Suspendisse accumsan tortor quis turpis.');
insert into review (id, bookingId, Rating, comment) values (132, 613, 4, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into review (id, bookingId, Rating, comment) values (133, 49, 3, 'Nulla nisl.');
insert into review (id, bookingId, Rating, comment) values (134, 694, 4, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into review (id, bookingId, Rating, comment) values (135, 387, 3, 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into review (id, bookingId, Rating, comment) values (136, 152, 1, 'Mauris lacinia sapien quis libero.');
insert into review (id, bookingId, Rating, comment) values (137, 687, 5, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into review (id, bookingId, Rating, comment) values (138, 338, 2, 'Donec vitae nisi.');
insert into review (id, bookingId, Rating, comment) values (139, 674, 2, 'Nunc purus.');
insert into review (id, bookingId, Rating, comment) values (140, 210, 4, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into review (id, bookingId, Rating, comment) values (141, 530, 4, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into review (id, bookingId, Rating, comment) values (142, 58, 3, 'Etiam pretium iaculis justo.');
insert into review (id, bookingId, Rating, comment) values (143, 269, 1, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into review (id, bookingId, Rating, comment) values (144, 241, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into review (id, bookingId, Rating, comment) values (145, 183, 1, 'Aenean sit amet justo.');
insert into review (id, bookingId, Rating, comment) values (146, 87, 3, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into review (id, bookingId, Rating, comment) values (147, 282, 5, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (148, 230, 1, 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into review (id, bookingId, Rating, comment) values (149, 288, 4, 'Etiam justo.');
insert into review (id, bookingId, Rating, comment) values (150, 73, 4, 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into review (id, bookingId, Rating, comment) values (151, 7, 4, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into review (id, bookingId, Rating, comment) values (152, 56, 4, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into review (id, bookingId, Rating, comment) values (153, 504, 2, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into review (id, bookingId, Rating, comment) values (154, 309, 4, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into review (id, bookingId, Rating, comment) values (155, 267, 4, 'Integer ac neque.');
insert into review (id, bookingId, Rating, comment) values (156, 301, 1, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (157, 441, 4, 'Etiam pretium iaculis justo.');
insert into review (id, bookingId, Rating, comment) values (158, 175, 5, 'Sed ante.');
insert into review (id, bookingId, Rating, comment) values (159, 526, 3, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into review (id, bookingId, Rating, comment) values (160, 178, 4, 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into review (id, bookingId, Rating, comment) values (161, 335, 5, 'Nullam varius.');
insert into review (id, bookingId, Rating, comment) values (162, 456, 5, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into review (id, bookingId, Rating, comment) values (163, 465, 5, 'Pellentesque viverra pede ac diam.');
insert into review (id, bookingId, Rating, comment) values (164, 364, 3, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into review (id, bookingId, Rating, comment) values (165, 328, 5, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into review (id, bookingId, Rating, comment) values (166, 255, 2, 'Nulla suscipit ligula in lacus.');
insert into review (id, bookingId, Rating, comment) values (167, 317, 3, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (168, 534, 2, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into review (id, bookingId, Rating, comment) values (169, 173, 3, 'Maecenas tincidunt lacus at velit.');
insert into review (id, bookingId, Rating, comment) values (170, 394, 2, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into review (id, bookingId, Rating, comment) values (171, 387, 3, 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into review (id, bookingId, Rating, comment) values (172, 47, 1, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into review (id, bookingId, Rating, comment) values (173, 207, 3, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into review (id, bookingId, Rating, comment) values (174, 58, 4, 'Etiam vel augue.');
insert into review (id, bookingId, Rating, comment) values (175, 221, 1, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into review (id, bookingId, Rating, comment) values (176, 574, 1, 'Nam nulla.');
insert into review (id, bookingId, Rating, comment) values (177, 99, 3, 'Nullam molestie nibh in lectus.');
insert into review (id, bookingId, Rating, comment) values (178, 221, 3, 'Fusce consequat.');
insert into review (id, bookingId, Rating, comment) values (179, 216, 1, 'Fusce consequat. Nulla nisl.');
insert into review (id, bookingId, Rating, comment) values (180, 640, 1, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (181, 392, 2, 'In blandit ultrices enim.');
insert into review (id, bookingId, Rating, comment) values (182, 74, 4, 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into review (id, bookingId, Rating, comment) values (183, 323, 2, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into review (id, bookingId, Rating, comment) values (184, 536, 2, 'Vivamus tortor.');
insert into review (id, bookingId, Rating, comment) values (185, 671, 4, 'Ut tellus.');
insert into review (id, bookingId, Rating, comment) values (186, 636, 1, 'Vestibulum rutrum rutrum neque.');
insert into review (id, bookingId, Rating, comment) values (187, 199, 4, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into review (id, bookingId, Rating, comment) values (188, 385, 2, 'Sed ante. Vivamus tortor.');
insert into review (id, bookingId, Rating, comment) values (189, 503, 3, 'Nulla mollis molestie lorem.');
insert into review (id, bookingId, Rating, comment) values (190, 654, 2, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into review (id, bookingId, Rating, comment) values (191, 160, 2, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into review (id, bookingId, Rating, comment) values (192, 301, 3, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into review (id, bookingId, Rating, comment) values (193, 103, 4, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into review (id, bookingId, Rating, comment) values (194, 463, 4, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into review (id, bookingId, Rating, comment) values (195, 483, 4, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into review (id, bookingId, Rating, comment) values (196, 385, 4, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into review (id, bookingId, Rating, comment) values (197, 645, 4, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into review (id, bookingId, Rating, comment) values (198, 347, 3, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into review (id, bookingId, Rating, comment) values (199, 309, 1, 'Morbi a ipsum.');
insert into review (id, bookingId, Rating, comment) values (200, 554, 5, 'Pellentesque eget nunc.');
insert into review (id, bookingId, Rating, comment) values (201, 675, 1, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into review (id, bookingId, Rating, comment) values (202, 645, 4, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into review (id, bookingId, Rating, comment) values (203, 8, 2, 'Vivamus tortor.');
insert into review (id, bookingId, Rating, comment) values (204, 347, 3, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into review (id, bookingId, Rating, comment) values (205, 347, 5, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into review (id, bookingId, Rating, comment) values (206, 15, 2, 'Praesent blandit.');
insert into review (id, bookingId, Rating, comment) values (207, 531, 1, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (208, 36, 1, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into review (id, bookingId, Rating, comment) values (209, 432, 2, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into review (id, bookingId, Rating, comment) values (210, 610, 3, 'Aliquam non mauris. Morbi non lectus.');
insert into review (id, bookingId, Rating, comment) values (211, 128, 5, 'Curabitur in libero ut massa volutpat convallis.');
insert into review (id, bookingId, Rating, comment) values (212, 395, 1, 'Nam dui.');
insert into review (id, bookingId, Rating, comment) values (213, 499, 4, 'Maecenas ut massa quis augue luctus tincidunt.');
insert into review (id, bookingId, Rating, comment) values (214, 444, 1, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into review (id, bookingId, Rating, comment) values (215, 19, 4, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into review (id, bookingId, Rating, comment) values (216, 549, 4, 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into review (id, bookingId, Rating, comment) values (217, 617, 4, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into review (id, bookingId, Rating, comment) values (218, 671, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into review (id, bookingId, Rating, comment) values (219, 464, 5, 'Vivamus vestibulum sagittis sapien.');
insert into review (id, bookingId, Rating, comment) values (220, 395, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into review (id, bookingId, Rating, comment) values (221, 345, 3, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into review (id, bookingId, Rating, comment) values (222, 338, 2, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into review (id, bookingId, Rating, comment) values (223, 8, 4, 'Aliquam erat volutpat. In congue.');
insert into review (id, bookingId, Rating, comment) values (224, 109, 4, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into review (id, bookingId, Rating, comment) values (225, 514, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into review (id, bookingId, Rating, comment) values (226, 276, 3, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into review (id, bookingId, Rating, comment) values (227, 208, 3, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into review (id, bookingId, Rating, comment) values (228, 353, 3, 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into review (id, bookingId, Rating, comment) values (229, 698, 3, 'Donec ut dolor.');
insert into review (id, bookingId, Rating, comment) values (230, 215, 3, 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (231, 36, 1, 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into review (id, bookingId, Rating, comment) values (232, 696, 3, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into review (id, bookingId, Rating, comment) values (233, 324, 4, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into review (id, bookingId, Rating, comment) values (234, 435, 4, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into review (id, bookingId, Rating, comment) values (235, 104, 1, 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into review (id, bookingId, Rating, comment) values (236, 270, 3, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into review (id, bookingId, Rating, comment) values (237, 33, 2, 'Curabitur convallis.');
insert into review (id, bookingId, Rating, comment) values (238, 47, 3, 'Nulla ac enim.');
insert into review (id, bookingId, Rating, comment) values (239, 661, 3, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into review (id, bookingId, Rating, comment) values (240, 494, 1, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into review (id, bookingId, Rating, comment) values (241, 581, 5, 'Duis consequat dui nec nisi volutpat eleifend.');
insert into review (id, bookingId, Rating, comment) values (242, 167, 2, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into review (id, bookingId, Rating, comment) values (243, 518, 2, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into review (id, bookingId, Rating, comment) values (244, 560, 2, 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into review (id, bookingId, Rating, comment) values (245, 491, 5, 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into review (id, bookingId, Rating, comment) values (246, 140, 4, 'Donec ut mauris eget massa tempor convallis.');
insert into review (id, bookingId, Rating, comment) values (247, 677, 3, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into review (id, bookingId, Rating, comment) values (248, 667, 4, 'Integer tincidunt ante vel ipsum.');
insert into review (id, bookingId, Rating, comment) values (249, 512, 1, 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into review (id, bookingId, Rating, comment) values (250, 206, 3, 'Vivamus tortor. Duis mattis egestas metus.');
insert into review (id, bookingId, Rating, comment) values (251, 597, 2, 'Etiam pretium iaculis justo.');
insert into review (id, bookingId, Rating, comment) values (252, 175, 4, 'Phasellus sit amet erat. Nulla tempus.');
insert into review (id, bookingId, Rating, comment) values (253, 409, 3, 'Nulla justo.');
insert into review (id, bookingId, Rating, comment) values (254, 365, 5, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into review (id, bookingId, Rating, comment) values (255, 63, 2, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into review (id, bookingId, Rating, comment) values (256, 674, 4, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into review (id, bookingId, Rating, comment) values (257, 413, 3, 'Nunc purus. Phasellus in felis.');
insert into review (id, bookingId, Rating, comment) values (258, 428, 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into review (id, bookingId, Rating, comment) values (259, 22, 4, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into review (id, bookingId, Rating, comment) values (260, 19, 5, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into review (id, bookingId, Rating, comment) values (261, 418, 3, 'Suspendisse potenti. In eleifend quam a odio.');
insert into review (id, bookingId, Rating, comment) values (262, 393, 4, 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into review (id, bookingId, Rating, comment) values (263, 175, 4, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into review (id, bookingId, Rating, comment) values (264, 507, 2, 'Donec semper sapien a libero. Nam dui.');
insert into review (id, bookingId, Rating, comment) values (265, 274, 3, 'Nullam porttitor lacus at turpis.');
insert into review (id, bookingId, Rating, comment) values (266, 356, 4, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into review (id, bookingId, Rating, comment) values (267, 576, 4, 'Praesent blandit.');
insert into review (id, bookingId, Rating, comment) values (268, 73, 2, 'Praesent blandit. Nam nulla.');
insert into review (id, bookingId, Rating, comment) values (269, 454, 3, 'Praesent lectus.');
insert into review (id, bookingId, Rating, comment) values (270, 269, 5, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into review (id, bookingId, Rating, comment) values (271, 446, 2, 'Sed accumsan felis.');
insert into review (id, bookingId, Rating, comment) values (272, 296, 4, 'Phasellus in felis.');
insert into review (id, bookingId, Rating, comment) values (273, 436, 5, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into review (id, bookingId, Rating, comment) values (274, 592, 1, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into review (id, bookingId, Rating, comment) values (275, 591, 3, 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into review (id, bookingId, Rating, comment) values (276, 643, 5, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into review (id, bookingId, Rating, comment) values (277, 674, 1, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into review (id, bookingId, Rating, comment) values (278, 194, 5, 'Aenean lectus. Pellentesque eget nunc.');
insert into review (id, bookingId, Rating, comment) values (279, 172, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into review (id, bookingId, Rating, comment) values (280, 635, 1, 'Morbi quis tortor id nulla ultrices aliquet.');
insert into review (id, bookingId, Rating, comment) values (281, 338, 1, 'Nulla ac enim.');
insert into review (id, bookingId, Rating, comment) values (282, 282, 3, 'Suspendisse potenti. In eleifend quam a odio.');
insert into review (id, bookingId, Rating, comment) values (283, 72, 2, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into review (id, bookingId, Rating, comment) values (284, 200, 4, 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into review (id, bookingId, Rating, comment) values (285, 475, 2, 'Maecenas tincidunt lacus at velit.');
insert into review (id, bookingId, Rating, comment) values (286, 615, 3, 'Phasellus in felis. Donec semper sapien a libero.');
insert into review (id, bookingId, Rating, comment) values (287, 133, 5, 'Phasellus in felis. Donec semper sapien a libero.');
insert into review (id, bookingId, Rating, comment) values (288, 17, 2, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into review (id, bookingId, Rating, comment) values (289, 533, 3, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into review (id, bookingId, Rating, comment) values (290, 435, 3, 'In hac habitasse platea dictumst.');
insert into review (id, bookingId, Rating, comment) values (291, 144, 1, 'Duis aliquam convallis nunc.');
insert into review (id, bookingId, Rating, comment) values (292, 73, 2, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into review (id, bookingId, Rating, comment) values (293, 242, 3, 'Vestibulum rutrum rutrum neque.');
insert into review (id, bookingId, Rating, comment) values (294, 606, 2, 'Integer ac neque. Duis bibendum.');
insert into review (id, bookingId, Rating, comment) values (295, 317, 4, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into review (id, bookingId, Rating, comment) values (296, 407, 4, 'Phasellus sit amet erat. Nulla tempus.');
insert into review (id, bookingId, Rating, comment) values (297, 670, 5, 'Ut at dolor quis odio consequat varius.');
insert into review (id, bookingId, Rating, comment) values (298, 308, 4, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into review (id, bookingId, Rating, comment) values (299, 294, 4, 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into review (id, bookingId, Rating, comment) values (300, 530, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
